"""Pair the archived linear Owen boundary with an external condition proxy.

Only the external boundary coefficients change. The proxy was generated by
build_owen_source_condition_proxy.py and is not measured maternal condition.
No COTSMod transition, local production, internal connectivity, or default
setting changes in this experiment.
"""

using Pkg
const ROOT = normpath(joinpath(@__DIR__, "..", ".."))
Pkg.activate(joinpath(ROOT, "sandbox"))
cd(ROOT)

using ADRIA, CSV, DataFrames, Dates, Random, TOML
include(joinpath(@__DIR__, "cots_cycle_metrics.jl"))
include(joinpath(@__DIR__, "reef_observation_mapping.jl"))
include(joinpath(@__DIR__, "calibration_run.jl"))

const SEED = 20260930
const RUN_ID = get(ENV, "OWEN_SOURCE_CONDITION_RUN_ID",
    Dates.format(now(), "yyyymmddTHHMMSS") * "_owen_source_condition_screen")
occursin(r"^[A-Za-z0-9_.-]+$", RUN_ID) || error("Invalid run ID")
const OUT = joinpath(@__DIR__, "runs", RUN_ID)
ispath(OUT) && error("Refusing to overwrite $OUT")
mkpath(OUT)
const V2 = joinpath(ROOT, "sandbox", "data", "Lizard_Historical_v0.2")
const SCREEN = joinpath(@__DIR__, "runs", "20261001T162000_owen_embedded_mortality_screen")
const REPLICATES = joinpath(@__DIR__, "runs", "20261001T163000_owen_embedded_replicates")
const PROXY_RUN = joinpath(@__DIR__, "runs", "20261002T160100_owen_source_condition_proxy")
const BEST = joinpath(@__DIR__, "runs", "expanded_cotsconn_pilot_seed20260930",
    "best_summary.csv")
const GATE = joinpath(@__DIR__, "runs", "20261001T113401_lizard_domain_gate")
const OBS = joinpath(ROOT, "sandbox", "data", "reef_cots.csv")
const TARGETS = [
    (model="Lizard Island Reef", observed="Lizard Isles"),
    (model="MacGillivray Reef", observed="Macgillivray Reef"),
    (model="North Direction Reef", observed="North Direction Island"),
    (model="Eyrie Reef", observed="Eyrie Reef"),
]
const FLOW_NAMES = ["local_fecundity", "background_immigration", "internal_immigration",
    "external_immigration", "maturation", "retained_juveniles", "settlement_gate",
    "local_retention", "pelagic_survivors", "settled_recruits",
    "external_potential", "external_pelagic"]

function recorded_revision(path::String, env_key::String)::String
    haskey(ENV, env_key) && return ENV[env_key]
    try
        return git_revision(path)
    catch
        error("Git revision unavailable; set $env_key from `git rev-parse HEAD`")
    end
end

screen_meta = TOML.parsefile(joinpath(SCREEN, "metadata.toml"))
fecundity = 4Float64(screen_meta["matched_fecundity_pre_pelagic_ha_year"])
boundary = 4Float64(screen_meta["matched_boundary_pre_pelagic_ha_year"])
candidate = sort(CSV.read(BEST, DataFrame), :loss)[1, :]
gate_scores = CSV.read(joinpath(GATE, "scores.csv"), DataFrame)
scale_rows = gate_scores[(gate_scores.seed .== SEED) .&
    (gate_scores.treatment .== "v1_legacy_closed") .&
    (gate_scores.observation_treatment .== "raw"), :]
fixed_scales = Dict(String(row.reef_name) => Float64(row.observation_scale)
    for row in eachrow(scale_rows))
length(fixed_scales) == length(TARGETS) || error("Missing fixed scales")

ENV["ADRIA_COTS_CONNECTIVITY_DATASET"] = "owen_global_2018_2023"
ENV["ADRIA_COTS_CONNECTIVITY_MODE"] = "cots"
ENV["COTS_CONNECTIVITY_TEMPORAL_MODE"] = "sample"
ENV["COTS_CONNECTIVITY_SEED"] = string(SEED)
ENV["COTS_CALENDAR_START_YEAR"] = "1985"
ENV["COTS_ALLEE_THRESHOLD"] = "3.0"
ENV["COTS_EXTERNAL_PULSE"] = "false"
ENV["COTS_EXTERNAL_SOURCE_DENSITY"] = "0.0"
ENV["COTS_JUVENILE_STORAGE"] = "false"
ENV["COTS_HABITAT_MEDIATION"] = "false"
ENV["COTS_SEPARATED_RECRUITMENT"] = "true"
ENV["COTS_APPLY_LARVAL_SURVIVAL"] = "false"
ENV["COTS_SETTLEMENT_PROBABILITY"] = "1.0"
ENV["COTS_IMMIGRATION_SCALAR"] = "1.0"
ENV["COTS_INITIAL_MULTIPLIER"] = string(candidate.seed_mult)
ENV["COTS_SEED_FIRST_N"] = "10"
ENV["ADRIA_DEBUG_SEED_FIRST_N"] = "10"
ENV["COTS_LARVAL_FECUNDITY"] = string(fecundity)
ENV["COTS_EXTERNAL_OUTBREAK_PRODUCTION"] = string(boundary)
delete!(ENV, "COTS_INTERNAL_SETTLEMENT_BLACKOUT_START_YEAR")
delete!(ENV, "COTS_INTERNAL_SETTLEMENT_BLACKOUT_END_YEAR")

domain = ADRIA.load_domain(ADRIA.LizardDomain, V2, "historical")
mapping = load_reef_area_weights(domain, V2, [t.model for t in TARGETS])
forcing = domain.cots_forcing
linear_potential = copy(forcing.external_outbreak_potential)
linear_pelagic = copy(forcing.external_outbreak_pelagic)
proxy = CSV.read(joinpath(PROXY_RUN, "external_source_condition_boundary.csv"), DataFrame)
site_map = CSV.read(joinpath(V2, "cots_connectivity", "datasets",
    "owen_global_2018_2023", "annual_forcing", "site_reef_map.csv"), DataFrame)
reef_order = sort(unique(site_map[:, [:reef_index, :reef_id]]), :reef_index)
Int.(reef_order.reef_index) == collect(1:size(linear_potential, 1)) ||
    error("Unexpected reef index order")
reef_lookup = Dict(string(row.reef_id) => Int(row.reef_index) for row in eachrow(reef_order))
year_lookup = Dict(year => idx for (idx, year) in enumerate(forcing.outbreak_years))
hydro_lookup = Dict(year => idx for (idx, year) in enumerate(forcing.years))
proxy_potential = similar(linear_potential)
fill!(proxy_potential, NaN)
for row in eachrow(proxy)
    index = (reef_lookup[string(row.reef_id)], year_lookup[Int(row.calendar_year)],
        hydro_lookup[Int(row.hydrodynamic_year)])
    isfinite(proxy_potential[index...]) && error("Duplicate proxy boundary row")
    abs(linear_potential[index...] - Float64(row.linear)) <= 1e-10 ||
        error("Archived boundary mismatch at $(index)")
    proxy_potential[index...] = Float64(row.condition_proxy_coefficient)
end
all(isfinite, proxy_potential) || error("Incomplete proxy boundary")
size(proxy_potential) == size(linear_potential) || error("Proxy shape changed")

Random.seed!(SEED)
base_scenario = ADRIA.sample(domain, 2)[1:1, :]
defaults = ADRIA.param_table(domain)
for name in names(base_scenario)
    base_scenario[!, name] .= defaults[1, name]
    if name != "allee_threshold" && hasproperty(candidate, Symbol(name))
        base_scenario[!, name] .= candidate[Symbol(name)]
    end
end
base_scenario[!, :allee_threshold] .= 3.0
raw_obs = CSV.read(OBS, DataFrame)
archived = CSV.read(joinpath(REPLICATES, "trajectories.csv"), DataFrame)
archived = archived[(archived.seed .== SEED) .&
    (archived.treatment .== "embedded_joint_4x"), :]
nrow(archived) == 40length(TARGETS) || error("Incomplete archived baseline")

scores = DataFrame(treatment=String[], reef_name=String[], observation_treatment=String[],
    loss=Float64[], sim_peak_count=Int[], sim_peak_years=String[],
    sim_peak_heights_cpue=String[], matched_peaks=Int[])
trajectories = DataFrame(treatment=String[], reef_name=String[], year=Int[],
    forcing_year=Int[], adults_ha=Float64[], simulated_cpue=Float64[], coral_cover=Float64[])
flows = DataFrame(treatment=String[], reef_name=String[], year=Int[])
for name in FLOW_NAMES
    flows[!, name] = Float64[]
end
failures = DataFrame(treatment=String[], error=String[])

for treatment in ("joint4_reference", "external_condition_proxy")
    forcing.external_outbreak_potential .= treatment == "joint4_reference" ?
        linear_potential : proxy_potential
    forcing.external_outbreak_pelagic .= treatment == "joint4_reference" ?
        linear_pelagic : proxy_potential
    Random.seed!(SEED)
    try
        result = ADRIA.run_scenario(domain, base_scenario[1, :])
        years = Int.(result.cots_calendar_year)
        years == collect(1985:2024) || error("Unexpected model years")
        cover = dropdims(sum(result.raw; dims=(2, 3)); dims=(2, 3))
        for target in TARGETS
            reef = target.model
            m = mapping[reef]
            adults = aggregate_reef_density(Matrix(result.cots_log[:, 3, :]), m)
            coral = aggregate_reef_density(cover, m)
            reef_flows = [aggregate_reef_density(Matrix(result.cots_flow_log[:, channel, :]), m)
                for channel in 1:length(FLOW_NAMES)]
            if treatment == "joint4_reference"
                reference = sort(archived[archived.reef_name .== reef, :], :year)
                length(adults) == nrow(reference) || error("Baseline reef length mismatch")
                years == Int.(reference.year) || error("Baseline years changed")
                Int.(result.cots_forcing_year) == Int.(reference.forcing_year) ||
                    error("Baseline hydrodynamic years changed")
                all(isapprox.(adults, Float64.(reference.adults_ha); atol=1e-12, rtol=0)) ||
                    error("Baseline adult state changed")
                all(isapprox.(coral, Float64.(reference.coral_cover); atol=1e-12, rtol=0)) ||
                    error("Baseline coral state changed")
            end
            scale = fixed_scales[reef]
            for (idx, year) in enumerate(years)
                push!(trajectories, (treatment, reef, year,
                    Int(result.cots_forcing_year[idx]), adults[idx], adults[idx] * scale,
                    coral[idx]))
                push!(flows, (treatment, reef, year,
                    (values[idx] for values in reef_flows)...))
            end
            obs = sort(raw_obs[(raw_obs.reef_name .== target.observed) .&
                (raw_obs.year .>= 1985) .& (raw_obs.year .<= 2024), :], :year)
            obs_years = Int.(obs.year)
            obs_values = Float64.(obs.cotsptow)
            smoothed = calendar_moving_average(obs_years, obs_values; window_years=3)
            for (name, values) in (("raw", obs_values), ("smoothed_3y", smoothed))
                score = cots_cycle_score(years, adults, obs_years, values;
                    fixed_observation_scale=scale)
                window = (years .>= score.scoring_start_year) .&
                    (years .<= score.scoring_end_year)
                peaks = detect_cots_peaks(years[window], (adults .* scale)[window];
                    smooth_window_years=3)
                push!(scores, (treatment, reef, name, score.total_loss,
                    score.n_sim_peaks, join(score.sim_peak_years, ';'),
                    join(round.([p.value for p in peaks]; digits=5), ';'),
                    score.n_matched_peaks))
            end
        end
        println("Completed ", treatment)
    catch err
        push!(failures, (treatment, sprint(showerror, err, catch_backtrace())))
        println(stderr, "FAILED ", treatment, ": ", err)
    end
    flush(stdout)
    CSV.write(joinpath(OUT, "scores.csv"), scores)
    CSV.write(joinpath(OUT, "trajectories.csv"), trajectories)
    CSV.write(joinpath(OUT, "flows.csv"), flows)
    CSV.write(joinpath(OUT, "failures.csv"), failures)
end

metadata = Dict(
    "status" => "external_source_condition_proxy_screen_not_promoted",
    "seed" => SEED,
    "proxy_warning" => "lagged 1-p is not measured coral or maternal condition; external adult density/fertilisation untested",
    "boundary_intervention" => "replace only external potential/pelagic coefficients with precomputed source-specific p*q^2 proxy, globally late-wave normalized",
    "fixed_allee_threshold_cots_ha" => 3.0,
    "fecundity_pre_pelagic_recruits_per_adult_year" => fecundity,
    "boundary_pre_pelagic_recruits_per_ha_year" => boundary,
    "reference_replay" => "adult, coral, and hydrodynamic year checked against archived seed-20260930 joint4",
    "julia_version" => string(VERSION),
    "adria_revision" => recorded_revision(ROOT, "OWEN_ADRIA_REVISION"),
    "cotsmod_revision" => recorded_revision(joinpath(ROOT, "..", "COTSMod.jl"),
        "OWEN_COTSMOD_REVISION"),
    "inputs" => Dict(
        "screen_metadata" => file_sha256(joinpath(SCREEN, "metadata.toml")),
        "reference_trajectories" => file_sha256(joinpath(REPLICATES, "trajectories.csv")),
        "candidate" => file_sha256(BEST),
        "gate_scores" => file_sha256(joinpath(GATE, "scores.csv")),
        "observations" => file_sha256(OBS),
        "proxy_boundary" => file_sha256(joinpath(PROXY_RUN, "external_source_condition_boundary.csv")),
        "proxy_metadata" => file_sha256(joinpath(PROXY_RUN, "metadata.json")),
        "script" => file_sha256(@__FILE__),
        "adapter" => file_sha256(joinpath(ROOT, "ADRIA", "src", "ecosystem", "cots.jl")),
        "core" => file_sha256(joinpath(ROOT, "..", "COTSMod.jl", "src", "COTSMod.jl")),
        "owen_forcing" => file_sha256(joinpath(V2, "cots_connectivity", "datasets",
            "owen_global_2018_2023", "provenance.json")),
    ),
    "outputs" => Dict(file => file_sha256(joinpath(OUT, file)) for file in
        ("scores.csv", "trajectories.csv", "flows.csv", "failures.csv")),
)
open(joinpath(OUT, "metadata.toml"), "w") do io
    TOML.print(io, metadata; sorted=true)
end
println("Saved ", OUT)
