name: UnitTests
on:
  # Trigger manually or on version tags
  push:
    tags:
      - 'v*'
  # Run in PR when packages updated
  pull_request:
    paths:
      - 'ADRIA/Manifest-v1.11.toml'
  workflow_dispatch:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.11"
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
        with:
          cache-name: adria-setup-cache
      - uses: julia-actions/julia-buildpkg@v1
        with:
          project: ADRIA
      - uses: julia-actions/julia-runtest@v1
        with:
          project: ADRIA
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: ADRIA/src
      - uses: codecov/codecov-action@v7
        with:
          verbose: true
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
